---
abstract: "Retrieve PDF image and text data via MuPDF's mutool"
author:
  - 'Project Renard'
build_requires:
  Data::DPath: '0'
  Renard::Incunabula::Devel::TestHelper: '0'
  Test::Most: '0'
  lib: '0'
  perl: '5.013002'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.013002'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-API-MuPDF-mutool
recommends:
  DateTime: '0'
requires:
  Alien::MuPDF: '0.007'
  Capture::Tiny: '0'
  Encode: '0'
  Log::Any: '0'
  Moo: '0'
  Path::Tiny: '0'
  Regexp::Common: '0'
  Renard::Incunabula::Common::Setup: '0'
  Renard::Incunabula::Common::Types: '0'
  XML::Simple: '0'
  constant: '0'
  overload: '0'
  perl: '5.013002'
  utf8: '0'
resources:
  homepage: https://github.com/project-renard/p5-Renard-API-MuPDF-mutool
  repository: https://github.com/project-renard/p5-Renard-API-MuPDF-mutool.git
version: 0.005_01
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
